
=head1 PRANG CHANGES

This POD file documents a summary of the changes in PRANG.  For the
full list of changes, refer to the git history.

=head2 VERSION 0.08 - 7 May 2010

=over

=item *

Distribution now includes all the modules required only for the tests.
This, along with a bugfix in L<Scriptalicious>, should hopefully close
the last of the CPAN testers failures for 0.07.

=item *

An addition to L<PRANG::XMLSchema::Types> Str subtypes: C<date>,
C<time>, and tightening of the C<dateTime> (it was not anchored
before, so accepted any string containing a dateTime).

=back

=head2 VERSION 0.07 - 26 Apr 2010

=over

=item *

New documentation B<PRANG::XMLSchema::Guide> which provides
information on manually converting XML Schema specifications to PRANG
classes.

=item *

Add a coerce rule for C<PRANG::XMLSchema::token> types which
normalizes whitespace on input values if enabled.

=item *

The C<xmlns> Class property now affects all sub-properties, but not
the including element.  This mirrors the default behaviour with XML
Schema.

=back

=head2 VERSION 0.06 - 14 Apr 2010

=over

=item *

Correct the handling of attributes with no prefix.  They should always
be considered to have no namespace, even if a default xmlns is
defined, apparently.

=back

=head2 VERSION 0.05 - 14 Apr 2010

=over

=item *

XML namespaces support is now much more complete; lots of cases,
including wildcarding of both the node name and the XML namespace now
work.  This is powerful enough to successfully round-trip crazy XML
Schema specifications such as C<E<lt>any namespace="##any"
processContents="skip"/E<gt>>

=item *

L<PRANG::Graph::Class> has been deprecated / ripped out.  It was a
hang-over from the time before C<use PRANG::Graph;> set up the
metaclass trait.

=item *

It is no longer required to specify the C<xmlns> method, if you do not
wish to use namespaces.

=item *

Specifying a role as a type now works, so long as the role is used by
only L<PRANG::Graph> types.

=back

=head2 VERSION 0.04 - 9 Apr 2010

=over

=item *

Much enhanced support for XML namespaces.  Tests and functionality
added; still lacking is the "Whatever" mapping, required for crazy
XMLSchema stuff like C<E<gt>any namespace="##any"
processContents="skip"/E<lt>> - this will be supported in the next
release.

=item *

Various bug fixes, more rejection of invalid input, and so on.

=back

=head2 VERSION 0.03 - 7 Apr 2010

=over

=item *

Some error message enhancements for from various forms of API
misunderstanding.

=item *

more missing dependencies added.

=back

=head2 VERSION 0.02 - 25 Mar 2010

=over

=item *

Back-port to work on pre-1.70 XML::LibXML

=item *

some missing dependencies added.

=back

=head1 SEE ALSO

L<PRANG>

=head1 COPYRIGHT

Copyright 2010, NZ Registry Services.  This documentation is licensed
under the Artistic License v2.0, which permits relicensing under other
Free Software licenses.

=cut
